# Generated by Django 2.0.2 on 2018-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_account', '0004_auto_20180209_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
